apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  namespace: nfs
  labels:
    app: nfs-server
spec:
  containers:
    - name: nfs-server
      image: itsthenetwork/nfs-server-alpine
      securityContext:
        privileged: true
      env:
        - name: SHARED_DIRECTORY
          value: /exports
      ports:
        - containerPort: 2049
      volumeMounts:
        - name: nfs-volume
          mountPath: /exports

  volumes:
    - name: nfs-volume
      emptyDir: {}